---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: nginx
          ports:
            - containerPort: 80
        - name: rss-reader
          image: tle249/jekin
          ports:
            - containerPort: 88